import type {
  TaskType,
  WorkbenchModelDto,
  WorkbenchSceneDto,
} from '../../../../../../packages/shared-types/src'

const commonTaskTypes: TaskType[] = ['clothes', 'real', 'mannequin', 'model_replace']

export const workbenchModels: WorkbenchModelDto[] = [
  {
    id: 'wm-1',
    name: 'Lena',
    code: 'lena-commercial',
    cover_image_url: 'https://picsum.photos/seed/wm-lena/480/640',
    tags: ['women', 'ecommerce', 'catalog'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-lena/480/640',
    race: 'western',
    age: 'young',
    style: ['business', 'street'],
    bodyType: 'standard',
    skinTone: 'natural',
    hairColor: 'brown',
    favorite: true,
  },
  {
    id: 'wm-2',
    name: 'Mia',
    code: 'mia-commute',
    cover_image_url: 'https://picsum.photos/seed/wm-mia/480/640',
    tags: ['women', 'commute', 'lookbook'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-mia/480/640',
    race: 'asian',
    age: 'young',
    style: ['sweet', 'commute'],
    bodyType: 'slim',
    skinTone: 'fair',
    hairColor: 'black',
    favorite: true,
  },
  {
    id: 'wm-3',
    name: 'Noah',
    code: 'noah-sport',
    cover_image_url: 'https://picsum.photos/seed/wm-noah/480/640',
    tags: ['men', 'sport', 'street'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-noah/480/640',
    race: 'western',
    age: 'young',
    style: ['sport', 'casual'],
    bodyType: 'fit',
    skinTone: 'wheat',
    hairColor: 'blond',
    favorite: false,
  },
  {
    id: 'wm-4',
    name: 'Sora',
    code: 'sora-ecommerce',
    cover_image_url: 'https://picsum.photos/seed/wm-sora/480/640',
    tags: ['women', 'ecommerce', 'clean'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-sora/480/640',
    race: 'asian',
    age: 'young',
    style: ['sweet', 'catalog'],
    bodyType: 'standard',
    skinTone: 'natural',
    hairColor: 'black',
    favorite: false,
  },
  {
    id: 'wm-5',
    name: 'Ella',
    code: 'ella-premium',
    cover_image_url: 'https://picsum.photos/seed/wm-ella/480/640',
    tags: ['women', 'premium', 'campaign'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-ella/480/640',
    race: 'western',
    age: 'mature',
    style: ['luxury', 'campaign'],
    bodyType: 'tall',
    skinTone: 'fair',
    hairColor: 'gold',
    favorite: true,
  },
  {
    id: 'wm-6',
    name: 'Yuki',
    code: 'yuki-fresh',
    cover_image_url: 'https://picsum.photos/seed/wm-yuki/480/640',
    tags: ['women', 'fresh', 'lifestyle'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-yuki/480/640',
    race: 'asian',
    age: 'young',
    style: ['j-style', 'fresh'],
    bodyType: 'slim',
    skinTone: 'fair',
    hairColor: 'brown',
    favorite: false,
  },
  {
    id: 'wm-7',
    name: 'Ava',
    code: 'ava-plus',
    cover_image_url: 'https://picsum.photos/seed/wm-ava/480/640',
    tags: ['women', 'plus', 'casual'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-ava/480/640',
    race: 'western',
    age: 'adult',
    style: ['plus', 'comfort'],
    bodyType: 'plus',
    skinTone: 'natural',
    hairColor: 'black',
    favorite: false,
  },
  {
    id: 'wm-8',
    name: 'Chen',
    code: 'chen-formal',
    cover_image_url: 'https://picsum.photos/seed/wm-chen/480/640',
    tags: ['men', 'formal', 'business'],
    supported_task_types: commonTaskTypes,
    avatar: 'https://picsum.photos/seed/wm-chen/480/640',
    race: 'asian',
    age: 'mature',
    style: ['business', 'formal'],
    bodyType: 'standard',
    skinTone: 'natural',
    hairColor: 'black',
    favorite: false,
  },
]

export const workbenchScenes: WorkbenchSceneDto[] = [
  {
    id: 'ws-1',
    name: 'Mall',
    code: 'mall',
    preview_image_url: 'https://picsum.photos/seed/ws-mall/960/1280',
    prompt_hint: 'Good for indoor commercial scenes and premium catalog shots.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-mall/640/400',
    type: 'indoor-commerce',
    tone: 'warm',
    lighting: 'ambient',
    style: 'campaign',
    usageCount: 1280,
  },
  {
    id: 'ws-2',
    name: 'Street',
    code: 'street',
    preview_image_url: 'https://picsum.photos/seed/ws-street/960/1280',
    prompt_hint: 'Good for outdoor urban lookbook and lifestyle scenes.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-street/640/400',
    type: 'urban-outdoor',
    tone: 'natural',
    lighting: 'natural',
    style: 'street',
    usageCount: 2340,
  },
  {
    id: 'ws-3',
    name: 'Overseas Block',
    code: 'overseas-block',
    preview_image_url: 'https://picsum.photos/seed/ws-overseas/960/1280',
    prompt_hint: 'Suitable for western street shots and fashion campaign visuals.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-overseas/640/400',
    type: 'urban-outdoor',
    tone: 'cool',
    lighting: 'side',
    style: 'brand-visual',
    usageCount: 860,
  },
  {
    id: 'ws-4',
    name: 'Studio White',
    code: 'studio-white',
    preview_image_url: 'https://picsum.photos/seed/ws-studio/960/1280',
    prompt_hint: 'Best for ecommerce main images and standard catalog outputs.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-studio/640/400',
    type: 'studio',
    tone: 'neutral',
    lighting: 'soft-key',
    style: 'ecommerce',
    usageCount: 4120,
  },
  {
    id: 'ws-5',
    name: 'Outdoor Natural',
    code: 'outdoor-natural',
    preview_image_url: 'https://picsum.photos/seed/ws-outdoor/960/1280',
    prompt_hint: 'Works well for lifestyle photos and fresh natural light looks.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-outdoor/640/400',
    type: 'outdoor-natural',
    tone: 'fresh',
    lighting: 'natural',
    style: 'lifestyle',
    usageCount: 1560,
  },
  {
    id: 'ws-6',
    name: 'Brand Set',
    code: 'brand-set',
    preview_image_url: 'https://picsum.photos/seed/ws-brand/960/1280',
    prompt_hint: 'Used for premium brand campaign shots and stronger art direction.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-brand/640/400',
    type: 'commercial-studio',
    tone: 'premium',
    lighting: 'rim',
    style: 'campaign',
    usageCount: 720,
  },
  {
    id: 'ws-7',
    name: 'Minimal Room',
    code: 'minimal-room',
    preview_image_url: 'https://picsum.photos/seed/ws-minimal/960/1280',
    prompt_hint: 'Simple indoor scene for calm layouts and editorial styling.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-minimal/640/400',
    type: 'indoor',
    tone: 'cool',
    lighting: 'top',
    style: 'minimal',
    usageCount: 980,
  },
  {
    id: 'ws-8',
    name: 'City Rooftop',
    code: 'city-rooftop',
    preview_image_url: 'https://picsum.photos/seed/ws-rooftop/960/1280',
    prompt_hint: 'Fashion-forward rooftop scene for trend and youth campaign outputs.',
    supported_task_types: commonTaskTypes,
    image: 'https://picsum.photos/seed/ws-rooftop/640/400',
    type: 'urban-outdoor',
    tone: 'warm',
    lighting: 'back',
    style: 'fashion',
    usageCount: 540,
  },
]
