-- FashionDesign business database schema.
-- Credits, balances, recharge orders, billing locks, and transaction ledger live in
-- reusable-credits-platform. This database stores vertical business data and
-- external credit-platform references/snapshots only.

CREATE DATABASE IF NOT EXISTS fashion_content_platform
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE fashion_content_platform;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(26) NOT NULL,
  phone_ciphertext VARBINARY(512) NULL,
  phone_hash CHAR(64) NULL,
  email_ciphertext VARBINARY(512) NULL,
  email_hash CHAR(64) NULL,
  password_hash VARCHAR(255) NULL,
  nickname VARCHAR(40) NOT NULL,
  avatar_asset_id CHAR(26) NULL,
  user_type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  register_source VARCHAR(20) NOT NULL,
  credits_platform_user_id BIGINT NULL,
  credit_account_id BIGINT NULL,
  credit_account_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  nickname_updated_at DATETIME(3) NULL,
  last_login_at DATETIME(3) NULL,
  last_login_ip VARCHAR(45) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_phone_hash (phone_hash),
  UNIQUE KEY uk_users_email_hash (email_hash),
  UNIQUE KEY uk_users_credits_platform_user (credits_platform_user_id),
  KEY idx_users_status_created (status, created_at),
  KEY idx_users_credit_account (credit_account_id),
  CHECK (user_type IN ('personal', 'enterprise')),
  CHECK (status IN ('active', 'frozen', 'deleted')),
  CHECK (register_source IN ('mobile', 'wechat', 'invite', 'admin')),
  CHECK (credit_account_status IN ('pending', 'ready', 'failed', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_oauth_bindings (
  id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  provider VARCHAR(20) NOT NULL,
  provider_openid VARCHAR(128) NOT NULL,
  provider_unionid VARCHAR(128) NULL,
  nickname_snapshot VARCHAR(100) NULL,
  avatar_url_snapshot VARCHAR(1024) NULL,
  access_scope VARCHAR(255) NULL,
  bound_at DATETIME(3) NOT NULL,
  last_login_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_oauth_provider_openid (provider, provider_openid),
  UNIQUE KEY uk_oauth_provider_unionid (provider, provider_unionid),
  KEY idx_oauth_user (user_id),
  CONSTRAINT fk_oauth_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS auth_sessions (
  id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  refresh_token_hash CHAR(64) NOT NULL,
  device_id VARCHAR(128) NULL,
  device_name VARCHAR(100) NULL,
  user_agent VARCHAR(512) NULL,
  ip_address VARCHAR(45) NULL,
  status VARCHAR(20) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  last_active_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  revoke_reason VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_auth_sessions_refresh_token_hash (refresh_token_hash),
  KEY idx_auth_sessions_user (user_id),
  KEY idx_auth_sessions_status_expires (status, expires_at),
  CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
  CHECK (status IN ('active', 'revoked', 'expired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS verification_codes (
  id CHAR(26) NOT NULL,
  target_hash CHAR(64) NOT NULL,
  purpose VARCHAR(32) NOT NULL,
  code_hash CHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  send_channel VARCHAR(20) NOT NULL,
  provider_message_id VARCHAR(128) NULL,
  ip_address VARCHAR(45) NULL,
  expires_at DATETIME(3) NOT NULL,
  verified_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_verification_codes_target (target_hash),
  KEY idx_verification_codes_status_expires (status, expires_at),
  CHECK (attempt_count >= 0),
  CHECK (status IN ('sent', 'verified', 'expired', 'blocked')),
  CHECK (send_channel IN ('sms', 'email'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS password_history (
  id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_password_history_user_created (user_id, created_at),
  CONSTRAINT fk_password_history_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS enterprises (
  id CHAR(26) NOT NULL,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(160) NOT NULL,
  industry VARCHAR(80) NULL,
  employee_scale VARCHAR(32) NULL,
  logo_asset_id CHAR(26) NULL,
  status VARCHAR(20) NOT NULL,
  owner_user_id CHAR(26) NOT NULL,
  credits_platform_tenant_id BIGINT NULL,
  credit_account_id BIGINT NULL,
  contact_name VARCHAR(60) NULL,
  contact_phone_ciphertext VARBINARY(512) NULL,
  contact_email_ciphertext VARBINARY(512) NULL,
  member_limit INT NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_enterprises_code (code),
  UNIQUE KEY uk_enterprises_credits_platform_tenant (credits_platform_tenant_id),
  KEY idx_enterprises_owner (owner_user_id),
  KEY idx_enterprises_credit_account (credit_account_id),
  KEY idx_enterprises_status_created (status, created_at),
  CONSTRAINT fk_enterprises_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
  CHECK (status IN ('pending', 'active', 'suspended', 'closed')),
  CHECK (member_limit > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS enterprise_members (
  id CHAR(26) NOT NULL,
  enterprise_id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  role_code VARCHAR(32) NOT NULL,
  status VARCHAR(20) NOT NULL,
  invited_by CHAR(26) NULL,
  joined_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_enterprise_members_enterprise_user (enterprise_id, user_id),
  KEY idx_enterprise_members_user (user_id),
  KEY idx_enterprise_members_invited_by (invited_by),
  CONSTRAINT fk_enterprise_members_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises (id),
  CONSTRAINT fk_enterprise_members_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_enterprise_members_inviter FOREIGN KEY (invited_by) REFERENCES users (id),
  CHECK (role_code IN ('owner', 'admin', 'member')),
  CHECK (status IN ('invited', 'active', 'disabled', 'removed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS enterprise_applications (
  id CHAR(26) NOT NULL,
  applicant_user_id CHAR(26) NOT NULL,
  enterprise_name VARCHAR(160) NOT NULL,
  contact_name VARCHAR(60) NOT NULL,
  contact_phone_ciphertext VARBINARY(512) NOT NULL,
  contact_email_ciphertext VARBINARY(512) NULL,
  industry VARCHAR(80) NULL,
  employee_scale VARCHAR(32) NULL,
  expected_usage TEXT NOT NULL,
  business_license_asset_id CHAR(26) NULL,
  status VARCHAR(20) NOT NULL,
  reviewer_user_id CHAR(26) NULL,
  review_note VARCHAR(1000) NULL,
  submitted_at DATETIME(3) NULL,
  reviewed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_enterprise_applications_applicant (applicant_user_id),
  KEY idx_enterprise_applications_reviewer (reviewer_user_id),
  KEY idx_enterprise_applications_status_created (status, created_at),
  CONSTRAINT fk_enterprise_applications_applicant FOREIGN KEY (applicant_user_id) REFERENCES users (id),
  CONSTRAINT fk_enterprise_applications_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS plans (
  id CHAR(26) NOT NULL,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(500) NULL,
  plan_type VARCHAR(20) NOT NULL,
  monthly_grant_credits DECIMAL(18,4) NOT NULL DEFAULT 0,
  single_task_concurrency INT NOT NULL,
  batch_task_concurrency INT NOT NULL,
  video_task_concurrency INT NOT NULL DEFAULT 0,
  member_limit INT NOT NULL DEFAULT 1,
  features_json JSON NOT NULL,
  status VARCHAR(20) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_plans_code (code),
  KEY idx_plans_status_sort (status, sort_order),
  CHECK (plan_type IN ('personal', 'enterprise')),
  CHECK (monthly_grant_credits >= 0),
  CHECK (single_task_concurrency >= 0),
  CHECK (batch_task_concurrency >= 0),
  CHECK (video_task_concurrency >= 0),
  CHECK (member_limit > 0),
  CHECK (status IN ('draft', 'active', 'inactive'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS plan_prices (
  id CHAR(26) NOT NULL,
  plan_id CHAR(26) NOT NULL,
  billing_cycle VARCHAR(20) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  list_price DECIMAL(12,2) NOT NULL,
  sale_price DECIMAL(12,2) NOT NULL,
  effective_from DATETIME(3) NOT NULL,
  effective_to DATETIME(3) NULL,
  status VARCHAR(20) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_plan_prices_plan_cycle_from (plan_id, billing_cycle, effective_from),
  KEY idx_plan_prices_plan_status (plan_id, status),
  CONSTRAINT fk_plan_prices_plan FOREIGN KEY (plan_id) REFERENCES plans (id),
  CHECK (billing_cycle IN ('monthly', 'yearly')),
  CHECK (list_price >= 0),
  CHECK (sale_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS credit_pricing_rules (
  id CHAR(26) NOT NULL,
  rule_version VARCHAR(32) NOT NULL,
  plan_code VARCHAR(32) NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  reusable_function_code VARCHAR(100) NOT NULL,
  unit VARCHAR(20) NOT NULL,
  unit_credits DECIMAL(18,4) NOT NULL,
  conditions_json JSON NULL,
  status VARCHAR(20) NOT NULL,
  effective_from DATETIME(3) NOT NULL,
  effective_to DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_pricing_rules_version (rule_version),
  KEY idx_pricing_rules_plan (plan_code),
  KEY idx_pricing_rules_task (task_type),
  KEY idx_pricing_rules_function (reusable_function_code),
  CHECK (unit IN ('image', 'video', 'task')),
  CHECK (unit_credits >= 0),
  CHECK (status IN ('draft', 'active', 'inactive'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_subscriptions (
  id CHAR(26) NOT NULL,
  owner_type VARCHAR(20) NOT NULL,
  owner_id CHAR(26) NOT NULL,
  plan_id CHAR(26) NOT NULL,
  plan_snapshot_json JSON NOT NULL,
  billing_cycle VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  start_at DATETIME(3) NOT NULL,
  end_at DATETIME(3) NOT NULL,
  auto_renew TINYINT(1) NOT NULL DEFAULT 0,
  credits_platform_payment_order_id BIGINT NULL,
  credits_grant_status VARCHAR(20) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_user_subscriptions_owner_status_end (owner_type, owner_id, status, end_at),
  KEY idx_user_subscriptions_plan (plan_id),
  KEY idx_user_subscriptions_payment_order (credits_platform_payment_order_id),
  CONSTRAINT fk_user_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans (id),
  CHECK (owner_type IN ('user', 'enterprise')),
  CHECK (billing_cycle IN ('monthly', 'yearly')),
  CHECK (status IN ('pending', 'active', 'expired', 'cancelled')),
  CHECK (credits_grant_status IN ('not_started', 'pending', 'success', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payment_order_snapshots (
  id CHAR(26) NOT NULL,
  credits_platform_payment_order_id BIGINT NOT NULL,
  order_no VARCHAR(100) NOT NULL,
  user_id CHAR(26) NOT NULL,
  enterprise_id CHAR(26) NULL,
  order_type VARCHAR(32) NOT NULL,
  subject VARCHAR(200) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  payment_channel VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  credit_account_id BIGINT NULL,
  credited_points DECIMAL(18,4) NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  paid_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_order_snapshots_platform_order (credits_platform_payment_order_id),
  UNIQUE KEY uk_payment_order_snapshots_order_no (order_no),
  KEY idx_payment_order_snapshots_user (user_id),
  KEY idx_payment_order_snapshots_enterprise (enterprise_id),
  KEY idx_payment_order_snapshots_status_created (status, created_at),
  CONSTRAINT fk_payment_order_snapshots_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_payment_order_snapshots_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises (id),
  CHECK (amount >= 0),
  CHECK (credited_points IS NULL OR credited_points >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ai_models (
  id CHAR(26) NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  cover_asset_id CHAR(26) NOT NULL,
  gallery_asset_ids JSON NULL,
  race VARCHAR(32) NULL,
  age_group VARCHAR(32) NULL,
  gender VARCHAR(20) NULL,
  style VARCHAR(32) NULL,
  body_type VARCHAR(32) NULL,
  skin_tone VARCHAR(32) NULL,
  hair_color VARCHAR(32) NULL,
  height_cm SMALLINT NULL,
  measurements_json JSON NULL,
  provider_model_ref VARCHAR(128) NULL,
  status VARCHAR(20) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_models_code (code),
  KEY idx_ai_models_status_sort (status, sort_order),
  CHECK (height_cm IS NULL OR height_cm > 0),
  CHECK (status IN ('draft', 'active', 'inactive'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS scenes (
  id CHAR(26) NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  cover_asset_id CHAR(26) NOT NULL,
  category VARCHAR(32) NULL,
  tone VARCHAR(32) NULL,
  lighting VARCHAR(32) NULL,
  prompt_template TEXT NULL,
  negative_prompt TEXT NULL,
  provider_scene_ref VARCHAR(128) NULL,
  status VARCHAR(20) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_scenes_code (code),
  KEY idx_scenes_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS generation_templates (
  id CHAR(26) NOT NULL,
  template_type VARCHAR(20) NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) NULL,
  cover_asset_id CHAR(26) NOT NULL,
  preview_asset_id CHAR(26) NULL,
  supported_task_types JSON NOT NULL,
  config_schema_json JSON NOT NULL,
  provider_config_json JSON NULL,
  status VARCHAR(20) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_generation_templates_code (code),
  KEY idx_generation_templates_type (template_type),
  KEY idx_generation_templates_status_sort (status, sort_order),
  CHECK (template_type IN ('action', 'video', 'creative'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_model_favorites (
  user_id CHAR(26) NOT NULL,
  model_id CHAR(26) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (user_id, model_id),
  CONSTRAINT fk_user_model_favorites_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_user_model_favorites_model FOREIGN KEY (model_id) REFERENCES ai_models (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_scene_favorites (
  user_id CHAR(26) NOT NULL,
  scene_id CHAR(26) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (user_id, scene_id),
  CONSTRAINT fk_user_scene_favorites_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_user_scene_favorites_scene FOREIGN KEY (scene_id) REFERENCES scenes (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS asset_folders (
  id CHAR(26) NOT NULL,
  owner_type VARCHAR(20) NOT NULL,
  owner_id CHAR(26) NOT NULL,
  parent_id CHAR(26) NULL,
  name VARCHAR(100) NOT NULL,
  path_cache VARCHAR(1000) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  active_unique_key TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uk_asset_folders_active_name (owner_type, owner_id, parent_id, name, active_unique_key),
  KEY idx_asset_folders_owner (owner_type, owner_id),
  KEY idx_asset_folders_parent (parent_id),
  CONSTRAINT fk_asset_folders_parent FOREIGN KEY (parent_id) REFERENCES asset_folders (id),
  CHECK (owner_type IN ('user', 'enterprise'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS assets (
  id CHAR(26) NOT NULL,
  owner_type VARCHAR(20) NOT NULL,
  owner_id CHAR(26) NOT NULL,
  folder_id CHAR(26) NULL,
  name VARCHAR(255) NOT NULL,
  original_file_name VARCHAR(255) NOT NULL,
  purpose VARCHAR(32) NOT NULL,
  media_type VARCHAR(20) NOT NULL,
  mime_type VARCHAR(128) NOT NULL,
  file_ext VARCHAR(16) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  sha256 CHAR(64) NOT NULL,
  storage_provider VARCHAR(20) NOT NULL,
  storage_bucket VARCHAR(128) NOT NULL,
  storage_key VARCHAR(1024) NOT NULL,
  public_url VARCHAR(1024) NULL,
  thumbnail_url VARCHAR(1024) NULL,
  width INT NULL,
  height INT NULL,
  duration_ms BIGINT NULL,
  metadata_json JSON NULL,
  review_status VARCHAR(20) NOT NULL,
  review_result_json JSON NULL,
  favorite TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_assets_owner_purpose_created (owner_type, owner_id, purpose, created_at),
  KEY idx_assets_owner_folder_created (owner_type, owner_id, folder_id, created_at),
  KEY idx_assets_owner_sha256 (owner_type, owner_id, sha256),
  KEY idx_assets_folder (folder_id),
  CONSTRAINT fk_assets_folder FOREIGN KEY (folder_id) REFERENCES asset_folders (id),
  CHECK (owner_type IN ('user', 'enterprise', 'system')),
  CHECK (media_type IN ('image', 'video', 'file')),
  CHECK (review_status IN ('pending', 'passed', 'rejected')),
  CHECK (status IN ('uploading', 'ready', 'failed', 'deleted')),
  CHECK (width IS NULL OR width > 0),
  CHECK (height IS NULL OR height > 0),
  CHECK (duration_ms IS NULL OR duration_ms >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS projects (
  id CHAR(26) NOT NULL,
  owner_type VARCHAR(20) NOT NULL,
  owner_id CHAR(26) NOT NULL,
  created_by CHAR(26) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description VARCHAR(1000) NULL,
  cover_asset_id CHAR(26) NULL,
  status VARCHAR(20) NOT NULL,
  task_count INT NOT NULL DEFAULT 0,
  last_activity_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_projects_owner_status_activity (owner_type, owner_id, status, last_activity_at),
  KEY idx_projects_created_by (created_by),
  KEY idx_projects_cover_asset (cover_asset_id),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_projects_cover_asset FOREIGN KEY (cover_asset_id) REFERENCES assets (id),
  CHECK (owner_type IN ('user', 'enterprise')),
  CHECK (status IN ('active', 'archived', 'deleted')),
  CHECK (task_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS task_quotes (
  id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  billing_owner_type VARCHAR(20) NOT NULL,
  billing_owner_id CHAR(26) NOT NULL,
  credit_account_id BIGINT NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  reusable_application_code VARCHAR(100) NOT NULL DEFAULT 'fashion-design',
  reusable_function_code VARCHAR(100) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  plan_code VARCHAR(32) NOT NULL,
  rule_version VARCHAR(32) NOT NULL,
  unit_credits DECIMAL(18,4) NOT NULL,
  billable_quantity DECIMAL(18,4) NOT NULL,
  estimated_credits DECIMAL(18,4) NOT NULL,
  config_snapshot_json JSON NOT NULL,
  status VARCHAR(20) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  used_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_task_quotes_user (user_id),
  KEY idx_task_quotes_owner_status (billing_owner_type, billing_owner_id, status),
  KEY idx_task_quotes_credit_account (credit_account_id),
  KEY idx_task_quotes_request_hash (request_hash),
  CONSTRAINT fk_task_quotes_user FOREIGN KEY (user_id) REFERENCES users (id),
  CHECK (billing_owner_type IN ('user', 'enterprise')),
  CHECK (status IN ('active', 'used', 'expired')),
  CHECK (unit_credits >= 0),
  CHECK (billable_quantity > 0),
  CHECK (estimated_credits >= 0),
  CHECK (task_type <> 'edit')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS generation_tasks (
  id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  owner_type VARCHAR(20) NOT NULL,
  owner_id CHAR(26) NOT NULL,
  project_id CHAR(26) NULL,
  parent_task_id CHAR(26) NULL,
  quote_id CHAR(26) NOT NULL,
  name VARCHAR(160) NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL,
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  stage VARCHAR(32) NULL,
  queue_priority INT NOT NULL DEFAULT 0,
  queue_position INT NULL,
  model_id CHAR(26) NULL,
  scene_id CHAR(26) NULL,
  template_id CHAR(26) NULL,
  config_json JSON NOT NULL,
  config_version VARCHAR(32) NOT NULL,
  billing_owner_type VARCHAR(20) NOT NULL,
  billing_owner_id CHAR(26) NOT NULL,
  credit_account_id BIGINT NOT NULL,
  billing_task_id BIGINT NULL,
  billing_status VARCHAR(24) NOT NULL,
  estimated_credits DECIMAL(18,4) NOT NULL,
  settled_credits DECIMAL(18,4) NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(2000) NULL,
  internal_error_detail TEXT NULL,
  retry_count INT NOT NULL DEFAULT 0,
  cancellable TINYINT(1) NOT NULL DEFAULT 1,
  deadline_at DATETIME(3) NULL,
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  version INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_generation_tasks_user_status_created (user_id, status, created_at),
  KEY idx_generation_tasks_owner_type_task_created (owner_type, owner_id, task_type, created_at),
  KEY idx_generation_tasks_status_deadline (status, deadline_at),
  KEY idx_generation_tasks_billing_status_updated (billing_status, updated_at),
  KEY idx_generation_tasks_billing_task (billing_task_id),
  KEY idx_generation_tasks_project (project_id),
  KEY idx_generation_tasks_parent (parent_task_id),
  KEY idx_generation_tasks_quote (quote_id),
  KEY idx_generation_tasks_model (model_id),
  KEY idx_generation_tasks_scene (scene_id),
  KEY idx_generation_tasks_template (template_id),
  CONSTRAINT fk_generation_tasks_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_generation_tasks_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_generation_tasks_parent FOREIGN KEY (parent_task_id) REFERENCES generation_tasks (id),
  CONSTRAINT fk_generation_tasks_quote FOREIGN KEY (quote_id) REFERENCES task_quotes (id),
  CONSTRAINT fk_generation_tasks_model FOREIGN KEY (model_id) REFERENCES ai_models (id),
  CONSTRAINT fk_generation_tasks_scene FOREIGN KEY (scene_id) REFERENCES scenes (id),
  CONSTRAINT fk_generation_tasks_template FOREIGN KEY (template_id) REFERENCES generation_templates (id),
  CHECK (owner_type IN ('user', 'enterprise')),
  CHECK (billing_owner_type IN ('user', 'enterprise')),
  CHECK (task_type <> 'edit'),
  CHECK (progress <= 100),
  CHECK (estimated_credits >= 0),
  CHECK (settled_credits IS NULL OR settled_credits >= 0),
  CHECK (retry_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS project_items (
  id CHAR(26) NOT NULL,
  project_id CHAR(26) NOT NULL,
  task_id CHAR(26) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  added_by CHAR(26) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_project_items_project_task (project_id, task_id),
  KEY idx_project_items_task (task_id),
  KEY idx_project_items_added_by (added_by),
  CONSTRAINT fk_project_items_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_project_items_task FOREIGN KEY (task_id) REFERENCES generation_tasks (id),
  CONSTRAINT fk_project_items_added_by FOREIGN KEY (added_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS task_inputs (
  id CHAR(26) NOT NULL,
  task_id CHAR(26) NOT NULL,
  asset_id CHAR(26) NOT NULL,
  input_role VARCHAR(32) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  snapshot_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_task_inputs_task (task_id),
  KEY idx_task_inputs_asset (asset_id),
  CONSTRAINT fk_task_inputs_task FOREIGN KEY (task_id) REFERENCES generation_tasks (id),
  CONSTRAINT fk_task_inputs_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
  CHECK (input_role IN ('primary', 'reference', 'logo'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS task_outputs (
  id CHAR(26) NOT NULL,
  task_id CHAR(26) NOT NULL,
  asset_id CHAR(26) NOT NULL,
  output_type VARCHAR(20) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  provider_output_ref VARCHAR(256) NULL,
  review_status VARCHAR(20) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_task_outputs_task (task_id),
  KEY idx_task_outputs_asset (asset_id),
  CONSTRAINT fk_task_outputs_task FOREIGN KEY (task_id) REFERENCES generation_tasks (id),
  CONSTRAINT fk_task_outputs_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
  CHECK (output_type IN ('image', 'video', 'preview')),
  CHECK (review_status IN ('pending', 'passed', 'rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS task_attempts (
  id CHAR(26) NOT NULL,
  task_id CHAR(26) NOT NULL,
  attempt_no INT NOT NULL,
  provider_code VARCHAR(32) NOT NULL,
  provider_model VARCHAR(128) NULL,
  status VARCHAR(20) NOT NULL,
  request_snapshot_json JSON NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(1000) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_attempts_task_attempt_no (task_id, attempt_no),
  CONSTRAINT fk_task_attempts_task FOREIGN KEY (task_id) REFERENCES generation_tasks (id),
  CHECK (attempt_no > 0),
  CHECK (status IN ('submitted', 'running', 'succeeded', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS provider_task_records (
  id CHAR(26) NOT NULL,
  task_id CHAR(26) NOT NULL,
  attempt_id CHAR(26) NOT NULL,
  provider_code VARCHAR(32) NOT NULL,
  provider_task_id VARCHAR(128) NOT NULL,
  provider_status VARCHAR(64) NULL,
  callback_event_id VARCHAR(128) NULL,
  last_response_json JSON NULL,
  last_polled_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_provider_task_records_provider_task (provider_code, provider_task_id),
  KEY idx_provider_task_records_task (task_id),
  KEY idx_provider_task_records_attempt (attempt_id),
  CONSTRAINT fk_provider_task_records_task FOREIGN KEY (task_id) REFERENCES generation_tasks (id),
  CONSTRAINT fk_provider_task_records_attempt FOREIGN KEY (attempt_id) REFERENCES task_attempts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS task_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id CHAR(26) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  from_status VARCHAR(24) NULL,
  to_status VARCHAR(24) NULL,
  progress TINYINT UNSIGNED NULL,
  payload_json JSON NULL,
  request_id VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_task_events_task_created (task_id, created_at),
  KEY idx_task_events_type_created (event_type, created_at),
  CONSTRAINT fk_task_events_task FOREIGN KEY (task_id) REFERENCES generation_tasks (id),
  CHECK (progress IS NULL OR progress <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS download_packages (
  id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  source_type VARCHAR(20) NOT NULL,
  source_id CHAR(26) NULL,
  asset_ids_json JSON NOT NULL,
  status VARCHAR(20) NOT NULL,
  storage_key VARCHAR(1024) NULL,
  download_url VARCHAR(1024) NULL,
  expire_at DATETIME(3) NULL,
  error_message VARCHAR(1000) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_download_packages_user_status_created (user_id, status, created_at),
  CONSTRAINT fk_download_packages_user FOREIGN KEY (user_id) REFERENCES users (id),
  CHECK (source_type IN ('task', 'project', 'selection')),
  CHECK (status IN ('pending', 'processing', 'ready', 'failed', 'expired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS delivery_requests (
  id CHAR(26) NOT NULL,
  request_no VARCHAR(64) NOT NULL,
  user_id CHAR(26) NOT NULL,
  enterprise_id CHAR(26) NULL,
  title VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  usage_scene VARCHAR(64) NOT NULL,
  style_tags_json JSON NULL,
  expected_delivery_at DATETIME(3) NULL,
  enterprise_name VARCHAR(160) NULL,
  contact_name VARCHAR(60) NOT NULL,
  contact_phone_ciphertext VARBINARY(512) NOT NULL,
  contact_email_ciphertext VARBINARY(512) NULL,
  status VARCHAR(32) NOT NULL,
  assigned_to CHAR(26) NULL,
  submitted_at DATETIME(3) NOT NULL,
  delivered_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_delivery_requests_request_no (request_no),
  KEY idx_delivery_requests_user (user_id),
  KEY idx_delivery_requests_enterprise (enterprise_id),
  KEY idx_delivery_requests_status_created (status, created_at),
  KEY idx_delivery_requests_assigned_to (assigned_to),
  CONSTRAINT fk_delivery_requests_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_delivery_requests_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises (id),
  CONSTRAINT fk_delivery_requests_assigned_to FOREIGN KEY (assigned_to) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS delivery_request_assets (
  id CHAR(26) NOT NULL,
  request_id CHAR(26) NOT NULL,
  asset_id CHAR(26) NOT NULL,
  asset_role VARCHAR(32) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_delivery_request_assets_request (request_id),
  KEY idx_delivery_request_assets_asset (asset_id),
  CONSTRAINT fk_delivery_request_assets_request FOREIGN KEY (request_id) REFERENCES delivery_requests (id),
  CONSTRAINT fk_delivery_request_assets_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
  CHECK (asset_role IN ('reference', 'logo', 'brand_package', 'result'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS delivery_status_logs (
  id CHAR(26) NOT NULL,
  request_id CHAR(26) NOT NULL,
  from_status VARCHAR(32) NULL,
  to_status VARCHAR(32) NOT NULL,
  note VARCHAR(2000) NULL,
  operator_type VARCHAR(20) NOT NULL,
  operator_user_id CHAR(26) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_delivery_status_logs_request_created (request_id, created_at),
  KEY idx_delivery_status_logs_operator (operator_user_id),
  CONSTRAINT fk_delivery_status_logs_request FOREIGN KEY (request_id) REFERENCES delivery_requests (id),
  CONSTRAINT fk_delivery_status_logs_operator FOREIGN KEY (operator_user_id) REFERENCES users (id),
  CHECK (operator_type IN ('user', 'staff', 'system'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS enterprise_leads (
  id CHAR(26) NOT NULL,
  source VARCHAR(32) NOT NULL,
  user_id CHAR(26) NULL,
  enterprise_name VARCHAR(160) NULL,
  contact_name VARCHAR(60) NOT NULL,
  contact_phone_ciphertext VARBINARY(512) NOT NULL,
  contact_email_ciphertext VARBINARY(512) NULL,
  requirement TEXT NOT NULL,
  preferred_contact_time VARCHAR(64) NULL,
  status VARCHAR(20) NOT NULL,
  assigned_to CHAR(26) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_enterprise_leads_status_created (status, created_at),
  KEY idx_enterprise_leads_user (user_id),
  KEY idx_enterprise_leads_assigned_to (assigned_to),
  CONSTRAINT fk_enterprise_leads_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_enterprise_leads_assigned_to FOREIGN KEY (assigned_to) REFERENCES users (id),
  CHECK (status IN ('new', 'contacted', 'qualified', 'closed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS notifications (
  id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  notification_type VARCHAR(32) NOT NULL,
  title VARCHAR(160) NOT NULL,
  content VARCHAR(2000) NOT NULL,
  biz_type VARCHAR(32) NULL,
  biz_id CHAR(26) NULL,
  action_url VARCHAR(1024) NULL,
  read_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_notifications_user_read_created (user_id, read_at, created_at),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS outbox_events (
  id CHAR(26) NOT NULL,
  aggregate_type VARCHAR(32) NOT NULL,
  aggregate_id CHAR(26) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(20) NOT NULL,
  retry_count INT NOT NULL DEFAULT 0,
  next_retry_at DATETIME(3) NULL,
  published_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_outbox_events_status_retry (status, next_retry_at),
  KEY idx_outbox_events_aggregate (aggregate_type, aggregate_id),
  CHECK (status IN ('pending', 'publishing', 'published', 'failed')),
  CHECK (retry_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS operation_audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  operator_type VARCHAR(20) NOT NULL,
  operator_id CHAR(26) NULL,
  action VARCHAR(64) NOT NULL,
  resource_type VARCHAR(32) NOT NULL,
  resource_id CHAR(26) NULL,
  before_json JSON NULL,
  after_json JSON NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(512) NULL,
  request_id VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_operation_audit_logs_resource (resource_type, resource_id),
  KEY idx_operation_audit_logs_operator (operator_type, operator_id),
  KEY idx_operation_audit_logs_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
